SET DOWNLOADS_PATH=C:\Users\%USERNAME%\Downloads
SET PICTURES=C:\Users\%USERNAME%\Pictures
SET DOCS=C:\Users\%USERNAME%\Documents
SET MUSIC=C:\Users\%USERNAME%\Music
SET VIDEOS=C:\Users\%USERNAME%\Videos

ECHO Pictures
MOVE %DOWNLOADS_PATH%\*.jpg %PICTURES%
MOVE %DOWNLOADS_PATH%\*.png %PICTURES%
MOVE %DOWNLOADS_PATH%\*.jpeg %PICTURES%
MOVE %DOWNLOADS_PATH%\*.png %PICTURES%
MOVE %DOWNLOADS_PATH%\*.ico %PICTURES%\Icons

ECHO Documents
MOVE %DOWNLOADS_PATH%\*.pdf %DOCS%
MOVE %DOWNLOADS_PATH%\*.html %DOCS%
MOVE %DOWNLOADS_PATH%\*.doc %DOCS%
MOVE DOWNLOADS_PATH\*.docx %DOCS%

ECHO Music
MOVE %DOWNLOADS_PATH%\*.mp3 %MUSIC%

ECHO Videos
MOVE %DOWNLOADS_PATH%\*.mp4 %VIDEOS%

EXIT

